version: '3'

# Analytics and monitoring tasks
tasks:
  analytics:events:
    desc: Show recent analytics events
    cmds:
      - sqlite3 {{.DB_FILE}} "SELECT * FROM events ORDER BY timestamp DESC LIMIT 10;" 2>/dev/null || echo "No events yet"

  analytics:summary:
    desc: Show analytics summary
    cmds:
      - cmd: |
          echo "📈 Analytics Summary:"
          echo ""
          echo "Events by type:"
          sqlite3 {{.DB_FILE}} "SELECT event_type, COUNT(*) FROM events GROUP BY event_type;" 2>/dev/null || echo "No events yet"

  payment:stats:
    desc: View payment statistics
    cmds:
      - cmd: |
          echo "💰 Payment Statistics:"
          echo ""
          sqlite3 {{.DB_FILE}} "SELECT status, COUNT(*), SUM(amount) FROM payments GROUP BY status;" 2>/dev/null || echo "No payments yet"

  payment:test:
    desc: Test Solana Pay integration (devnet)
    cmds:
      - cmd: |
          echo "Testing Solana Pay..."
          echo "Network: ${NEXT_PUBLIC_SOLANA_NETWORK:-devnet}"
          echo "Merchant: ${NEXT_PUBLIC_SOLANA_MERCHANT_ADDRESS:-not set}"

  calendar:test:
    desc: Test Google Calendar connection
    cmds:
      - cmd: |
          echo "Testing Google Calendar..."
          echo "Client ID: ${GOOGLE_CLIENT_ID:+configured}"
          echo "Client Secret: ${GOOGLE_CLIENT_SECRET:+configured}"
          echo "Refresh Token: ${GOOGLE_REFRESH_TOKEN:+configured}"
