version: '3'

# Database management tasks
tasks:
  db:init:
    desc: Initialize SQLite database
    cmds:
      - mkdir -p {{.DATA_DIR}}
      - touch {{.DB_FILE}}

  db:stats:
    desc: Show database statistics
    cmds:
      - cmd: |
          echo "📊 Database Statistics:"
          echo ""
          echo "Conversations:"
          sqlite3 {{.DB_FILE}} "SELECT COUNT(*) FROM conversations;" 2>/dev/null || echo "0"
          echo ""
          echo "Messages:"
          sqlite3 {{.DB_FILE}} "SELECT COUNT(*) FROM messages;" 2>/dev/null || echo "0"
          echo ""
          echo "Events:"
          sqlite3 {{.DB_FILE}} "SELECT COUNT(*) FROM events;" 2>/dev/null || echo "0"
          echo ""
          echo "Payments:"
          sqlite3 {{.DB_FILE}} "SELECT COUNT(*) FROM payments;" 2>/dev/null || echo "0"

  db:backup:
    desc: Backup database
    cmds:
      - cp {{.DB_FILE}} {{.DB_FILE}}.backup.{{now | date "2006-01-02-15-04-05"}}

  db:reset:
    desc: Reset database (WARNING - deletes all data)
    prompt: This will delete all data. Are you sure?
    cmds:
      - rm -f {{.DB_FILE}}
      - task: db:init
