version: '3'

# Development tasks
tasks:
  dev:
    desc: Start Next.js development server with Turbopack
    cmds:
      - '{{.PKG_MANAGER}} run dev'

  dev:watch:
    desc: Start dev server and watch for file changes
    cmds:
      - '{{.PKG_MANAGER}} run dev --turbo'

  install:
    desc: Install dependencies with Bun
    cmds:
      - '{{.PKG_MANAGER}} install'

  update:
    desc: Update dependencies
    cmds:
      - '{{.PKG_MANAGER}} update'

  clean:
    desc: Clean build artifacts and dependencies
    cmds:
      - rm -rf .next
      - rm -rf node_modules
      - rm -rf out

  clean:packages:
    desc: Clean all package build artifacts
    cmds:
      - rm -rf packages/*/dist
      - rm -rf packages/*/.turbo
      - echo "✅ Cleaned package artifacts"
