version: '3'

# Testing tasks
tasks:
  test:
    desc: Run all tests
    cmds:
      - task: test:e2e

  test:e2e:
    desc: Run E2E tests with Playwright
    cmds:
      - '{{.PKG_MANAGER}} run test:e2e'

  test:e2e:ui:
    desc: Run E2E tests with Playwright UI
    cmds:
      - '{{.PKG_MANAGER}} run test:e2e:ui'

  test:e2e:debug:
    desc: Debug E2E tests with Playwright
    cmds:
      - '{{.PKG_MANAGER}} run test:e2e:debug'

  test:e2e:headed:
    desc: Run E2E tests in headed mode (see browser)
    cmds:
      - '{{.PKG_MANAGER}} run test:e2e:headed'

  test:install:
    desc: Install Playwright browsers
    cmds:
      - '{{.PKG_MANAGER}} run test:install'
